version: '3'
services:
    backend-nginx:
        container_name: backend-nginx
        build:
            context: ./
            dockerfile: docker/nginx/Dockerfile
            args:
                VHOST_FILE: ${VHOST_FILE}
        volumes:
            - ./:/var/www
        ports:
            - 80
        depends_on:
            - backend-php
        environment:
            VIRTUAL_HOST: ${VIRTUAL_HOSTS}
            VIRTUAL_PORT: 80
            LETSENCRYPT_HOST: ${VIRTUAL_HOSTS}
            LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
        networks:
            - backend
            - nginx-proxy

    backend-php:
        user: ${USER_ID}:${GROUP_ID}
        container_name: backend-php
        build:
            context: ./
            dockerfile: docker/php/Dockerfile
            args:
                USER_ID: ${USER_ID}
                GROUP_ID: ${GROUP_ID}
        volumes:
            - ./:/var/www
        tmpfs:
            - /dev/shm
        ports:
            - 9000
        depends_on:
            - backend-mysql
            - backend-redis
        networks:
            - backend

    backend-mysql:
        container_name: backend-mysql
        build:
            context: ./
            dockerfile: docker/mysql/Dockerfile
        ports:
            - ${DB_EXTERNAL_PORT}:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
        command: --default-authentication-plugin=mysql_native_password
        networks:
            - backend

    backend-redis:
        container_name: backend-redis
        build:
            context: ./
            dockerfile: docker/redis/Dockerfile
            args:
                REDIS_PASSWORD: ${REDIS_PASSWORD}
        sysctls:
            - net.core.somaxconn=511
        ports:
            - ${REDIS_EXTERNAL_PORT}:6379
        networks:
            - backend

networks:
    backend:
    nginx-proxy:
        external: true
